YAML
name: python code

Trigger
on:
  push:
    branches: [main,]
  pull:
    branches: [main,]

jobs: 
 run-tests:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repository code
      uses: actions/checkout@v7
    - name: Setup Python environment
      uses: uses: durandtibo/setup-venv-uv-action@v0.0.3