YAML
name: python code

Trigger
on:
  push:
    branches: [main, feat/learning]
  pull_request:
    branches: [main, feat/learning]

jobs: 
 run-tests:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repository code
      uses: actions/checkout@v7

    - name: Setup Python environment
      uses: durandtibo/setup-venv-uv-action@v0.0.3

    - name: Run tests
        run: |
          python -m pytest